spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:commentsdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    queueName: commentsQueue
    exchangeName: commentsExchange
    routingKey: commentsKey
  data:
    elasticsearch:
      cluster-name: comments-service
